version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=security_user
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "mvn spring-boot:run"
    ports:
      - "8080:8080"
    depends_on:
      - db